FROM       ubuntu:16.04
MAINTAINER soonho.kong@gmail.com

RUN mkdir /dreal4
COPY . /dreal4
RUN cd /dreal4 \
      && sed -i "s/zlib1g-dev/zlib1g-dev\npython3.5\npython3.5-dev/" setup/ubuntu/16.04/install_prereqs.sh
RUN apt-get update && yes "Y" \
      | /dreal4/setup/ubuntu/16.04/install_prereqs.sh \
      && rm -rf /var/lib/apt/lists/* \
      && apt-get clean all	  
RUN cd /dreal4 \
      && sed -i "s/python-2/python-3.5/" tools/pybind11.BUILD.bazel \
      && bazel build //:archive \
      && tar xfz bazel-bin/archive.tar.gz
CMD ["python3"]
