# -*- python -*-
# This file contains rules for Bazel; see https://bazel.io/ .

load(
    "//tools:dreal.bzl",
    "dr_test",
)

dr_test(
    name = "car10dumped",
    size = "small",
)

dr_test(
    name = "logical_operator1",
    size = "small",
)

dr_test(
    name = "logical_operator2",
    size = "small",
)

dr_test(
    name = "logical_operator3",
    size = "small",
)

dr_test(
    name = "logical_operator4",
    size = "small",
)

dr_test(
    name = "pow",
    size = "small",
)

dr_test(
    name = "simple",
    size = "small",
)

dr_test(
    name = "smallctr",
    size = "small",
)

dr_test(
    name = "unary_minus",
    size = "small",
)
