name: Ubuntu_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build_test_jammy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cc: [gcc-9, gcc-10, gcc-11, gcc-12, clang-12, clang-13, clang-14]
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: setup
       run: sudo ./setup/ubuntu/22.04/install_prereqs.sh
     - name: build and test
       run: |
         CC=${{ matrix.cc }} bazel test //... \
         -c dbg \
         --test_output=errors \
         --verbose_failures

  build_test_focal:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cc: [gcc-9, gcc-10, clang-10, clang-11, clang-12]
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: setup
       run: sudo ./setup/ubuntu/20.04/install_prereqs.sh
     - name: build and test
       run: |
         CC=${{ matrix.cc }} bazel test //... \
         -c dbg \
         --test_output=errors \
         --verbose_failures

  ubsan_focal:
    runs-on: ubuntu-22.04
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: setup
       run: sudo ./setup/ubuntu/22.04/install_prereqs.sh
     - name: build and test
       run: |
         CC=clang-14 bazel test //... \
           -c dbg \
           --config ubsan \
           --test_output=errors \
           --test_tag_filters=-no_ubsan \
           --linkopt=-lgcc_s \
           --verbose_failures

  asan_focal:
    runs-on: ubuntu-22.04
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: setup
       run: sudo ./setup/ubuntu/22.04/install_prereqs.sh
     - name: build and test
       run: |
         CC=clang-14 bazel test //... \
           -c dbg \
           --config asan \
           --test_output=errors \
           --test_tag_filters=-no_asan \
           --verbose_failures
